WebApplication1/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class AlunosController : Controller
    {
        private readonly Contexto _context;

        public AlunosController(Contexto context)
        {
            _context = context;
        }

        // GET: Alunos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Alunos.ToListAsync());
        }

        public IActionResult Todos()
        {
            TodosViewModel todos = new TodosViewModel();
            todos.Alunos = _context.Alunos.ToList();
            todos.Materias = _context.Materias.ToList();

            return View(todos);
        }

        // GET: Alunos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos
                .FirstOrDefaultAsync(m => m.AlunosId == id);
            if (alunos == null)
            {
                return NotFound();
            }

            return View(alunos);
        }

        // GET: Alunos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlunosId,Nome")] Alunos alunos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alunos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alunos);
        }

        // GET: Alunos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos.FindAsync(id);
            if (alunos == null)
            {
                return NotFound();
            }
            return View(alunos);
        }

        // POST: Alunos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlunosId,Nome")] Alunos alunos)
        {
            if (id != alunos.AlunosId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alunos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunosExists(alunos.AlunosId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alunos);
        }

        // GET: Alunos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos
                .FirstOrDefaultAsync(m => m.AlunosId == id);
            if (alunos == null)
            {
                return NotFound();
            }

            return View(alunos);
        }

        // POST: Alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alunos = await _context.Alunos.FindAsync(id);
            _context.Alunos.Remove(alunos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunosExists(int id)
        {
            return _context.Alunos.Any(e => e.AlunosId == id);
        }
    }
}

WebApplication1/Controllers/CarrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CarrosController : Controller
    {
        private readonly Contexto _contexto;

        public CarrosController(Contexto contexto)
        {
            _contexto = contexto;
        }

        /// <summary>
        /// Abrir Tela Index
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {            
            return View(_contexto.Carros.ToList());
        }

        /// <summary>
        /// Abrir Novo Carro
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult NovoCarro()
        {
            return View();
        }

        /// <summary>
        /// Salvar na Tela Novo Carro
        /// </summary>
        /// <param name="carro"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NovoCarro(Carro carro)
        {
            if (ModelState.IsValid)
            {
                _contexto.Add(carro);
                _contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(carro);
        }

        /// <summary>
        /// Abrir Tela Atualiza Carro
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AtualizaCarro(int? id)
        {
            if (id.Equals(null))
                return NotFound();

            var carro = _contexto.Carros.Find(id);

            return View(carro);
        }

        /// <summary>
        /// Atualizar na Tela Atualiza Carro
        /// </summary>
        /// <param name="id"></param>
        /// <param name="carro"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AtualizaCarro(int id, Carro carro)
        {
            if (id.Equals(null))
                return NotFound();

            if (ModelState.IsValid)
            {
                _contexto.Update(carro);
                _contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(carro);
        }

        /// <summary>
        /// Abrir Tela Detalhes
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Detalhes(int? id)
        {
            if (id.Equals(null))
                return NotFound();
            
            var carro = _contexto.Carros.FirstOrDefault(x => x.CarroId.Equals(id));

            return View(carro);
        }

        /// <summary>
        /// Abrir Tela Exclui Carro
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id.Equals(null))
                return NotFound();

            var carro = _contexto.Carros.FirstOrDefault(x => x.CarroId.Equals(id));

            return View(carro);
        }

        /// <summary>
        /// Excluir na Tela Excluir Carro
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarExclusao(int id)
        {
            if (id.Equals(null))
                return NotFound();

            var carro = _contexto.Carros.FirstOrDefault(x => x.CarroId.Equals(id));
            _contexto.Remove(carro);
            _contexto.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplication1/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class MenuController : Controller
    {
        /// <summary>
        /// Abrir Tela Index
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/MoedasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class MoedasController : Controller
    {
        private readonly Contexto _context;

        public MoedasController(Contexto context)
        {
            _context = context;
        }

        // GET: Moedas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Moedas.ToListAsync());
        }

        public async Task<IActionResult> EscolhadeMoedas(List<Moedas> moedas)
        {
            foreach (var item in moedas)
            {
                if (item.CheckboxMarcado)
                {
                    Moedas moeda = await _context.Moedas.FirstAsync(x => x.MoedasId.Equals(item.MoedasId));
                    moeda.Quantidade += 1;
                    _context.Update(moeda);
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToAction(nameof(Index));
        }

        public JsonResult DadosGrafico()
        {
            return Json(_context.Moedas.Select(x => new { x.Nome, x.Quantidade }));
        }

        // GET: Moedas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Moedas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MoedasId,Nome,Quantidade")] Moedas moedas)
        {
            if (ModelState.IsValid)
            {
                moedas.Quantidade = 0;

                _context.Add(moedas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(moedas);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/bundle.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/lib/bundle.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Menu" asp-action="Index" class="navbar-brand">Menu</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Carros" asp-action="Index">Carros</a></li>
                    <li><a asp-area="" asp-controller="Tarefas" asp-action="Index">Tarefas</a></li>
                    <li><a asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a></li>
                    <li><a asp-area="" asp-controller="Moedas" asp-action="Index">Moedas</a></li>
                    <li><a asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a></li>
                    <li><a asp-area="" asp-controller="Cliente2" asp-action="Index">Cliente2</a></li>
                    <li><a asp-area="" asp-controller="Cliente3" asp-action="Index">Cliente3</a></li>
                    <li><a asp-area="" asp-controller="Person" asp-action="Index">Person</a></li>
                    <li><a asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a></li>
                    <li><a asp-area="" asp-controller="Materias" asp-action="Index">Materias</a></li>
                    <li><a asp-area="" asp-controller="Alunos" asp-action="Todos">Alunos e Materias</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/bundle.js" asp-append-version="true"></script>
        <script src="~/lib/Chart.js/Chart.bundle.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="~/lib/Chart.js/Chart.bundle.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/bundle.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>